

services:
  lean:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lean_workspace
    volumes:
      - .:/workspace
    tty: true
    stdin_open: true
    # Working inside the lean package by default
    working_dir: /workspace/lean
