/-
  Universitas Pandrosion — Lean 4 Formalization
  LANG ORBITAL MODULE

  Lang's density conjecture asserts that the set of integral points on an
  affine variety of general type is not Zariski dense. In dynamical
  analogy, if we look at the integral affine orbits generated by a generic
  morphism, they should be "sparse" globally.

  For the Pandrosion iteration, the orbit (A_n, B_n) generates a sequence
  of points in the affine plane. We formalize the "Lang sparsity" by proving
  that the affine orbit strictly escapes any compact affine region
  [-M, M] × [-M, M]. Thus, the "integral density" of the orbit acting on
  the affine plane is globally zero: the points inevitably diverge toward
  infinity, leaving every bounded variety devoid of long-term sequence
  members over Z.
-/
import Mathlib.Data.Int.Basic
import Mathlib.Tactic
import Pandrosion.EffectiveFaltingsOrbital

namespace Pandrosion

/-! ## §4100. Lang Density Extinction on the Affine Plane

The affine space containment for integer coordinate pairs (A, B) is
exactly characterized by the projective maximum height. The escape
of the height ensures the orbit cannot remain dense in any fixed affine
domain.
-/

/-- **Lang affine space escape.**
    If the affine space is bounded by M (i.e. |A| ≤ M and |B| ≤ M),
    then after a calculable, finite threshold index n₀, all subsequent
    orbital points (A_n, B_n) strictly exit the bounded space. -/
theorem lang_orbital_affine_escape
    (d : ℕ → ℤ) (Φ : ℕ → ℤ) (A B : ℕ → ℤ) (X : ℤ)
    (hd0 : d 0 ≠ 0)
    (hΦ : ∀ n, 2 ≤ |Φ n|)
    (hd : ∀ n, d (n + 1) = d n * Φ n)
    (h_norm : ∀ n, d n = A n ^ 3 - X * B n ^ 3)
    (hX : 0 ≤ |X|)
    (M : ℤ) (n : ℕ) (hn : (1 + |X|) * M ^ 3 - |d 0| < (n : ℤ)) :
    M < |A n| ∨ M < |B n| := by
  -- Suppose by contradiction that BOTH are ≤ M.
  have h_cases := le_or_lt (proj_height (A n) (B n)) M
  rcases h_cases with h_in | h_out
  · -- If in the box, Faltings effective bound gives n ≤ (1+|X|)M^3 - |d_0|
    apply False.elim
    have h_bound := faltings_orbital_box_extinction d Φ A B X hd0 hΦ hd h_norm hX M n h_in
    linarith
  · -- If out of the box, then either |A_n| > M or |B_n| > M
    unfold proj_height at h_out
    have h_or : M < |A n| ∨ M < |B n| := by
      have h_not_le : ¬ (max |A n| |B n| ≤ M) := by linarith
      have h_le_iff := max_le_iff (a := |A n|) (b := |B n|) (c := M)
      have h_not_and : ¬ (|A n| ≤ M ∧ |B n| ≤ M) := by
        intro h_and
        have : max |A n| |B n| ≤ M := h_le_iff.mpr h_and
        exact h_not_le this
      -- Now ¬(P ∧ Q) ↔ ¬P ∨ ¬Q ↔ M < |A| ∨ M < |B|
      omega
    exact h_or

end Pandrosion
