/-
  Strict axiom gate (generated section below).

  This file is NOT hand-maintained beyond this header. `scripts/strict_check.sh`
  generates the `#print axioms Pandrosion.<name>` block at build time by
  scanning every `theorem`/`lemma` declaration in `Pandrosion/*.lean`.

  The resulting `#print axioms` output is parsed to enforce:
    - zero `sorryAx`
    - every axiom outside {propext, Classical.choice, Quot.sound} is flagged.
-/
import Pandrosion

-- BEGIN GENERATED AXIOM AUDIT
#print axioms Pandrosion.D_neg
#print axioms Pandrosion.D_tendsto_neg_log2
#print axioms Pandrosion.D_two_eq
#print axioms Pandrosion.H3_derivative_numerator
#print axioms Pandrosion.H3_extra_fixed_den_ne_zero
#print axioms Pandrosion.H3_extra_fixed_is_fixed
#print axioms Pandrosion.H3_extra_fixed_multiplier_normSq_gt_one
#print axioms Pandrosion.H3_extra_fixed_multiplier_norm_gt_one
#print axioms Pandrosion.H3_extra_fixed_ne_one
#print axioms Pandrosion.H3_extra_fixed_ne_zero
#print axioms Pandrosion.H3_extra_fixed_not_converges_to_one
#print axioms Pandrosion.H3_fixed_iff
#print axioms Pandrosion.H3_fixed_not_converges_to_one
#print axioms Pandrosion.H3_fixed_sub_factor
#print axioms Pandrosion.H3_formal_multiplier_at_one
#print axioms Pandrosion.H3_formal_multiplier_extra_fixed_poly
#print axioms Pandrosion.H3_one_fixed
#print axioms Pandrosion.H3_real_coe
#print axioms Pandrosion.H3_real_error_identity
#print axioms Pandrosion.H3_zero_fixed
#print axioms Pandrosion.H3_zero_not_converges_to_one
#print axioms Pandrosion.P3_complex_cubic_coordinate
#print axioms Pandrosion.P3_complex_fixed_iff
#print axioms Pandrosion.P3_complex_root_fixed
#print axioms Pandrosion.P3_complex_zero_fixed
#print axioms Pandrosion.P3_derivative_numerator
#print axioms Pandrosion.Q_cubic_pos
#print axioms Pandrosion.Q_selfevaluation
#print axioms Pandrosion.Qp_le_Sp_mul
#print axioms Pandrosion.Qp_nonneg
#print axioms Pandrosion.Sp'_nonneg
#print axioms Pandrosion.Sp'_pos
#print axioms Pandrosion.Sp2_eq
#print axioms Pandrosion.Sp3_eq
#print axioms Pandrosion.Sp3_prod_bound
#print axioms Pandrosion.Sp3_sub
#print axioms Pandrosion.Sp4_prod_bound
#print axioms Pandrosion.Sp4_sub
#print axioms Pandrosion.Sp5_prod_bound
#print axioms Pandrosion.Sp5_sub
#print axioms Pandrosion.Sp_deriv
#print axioms Pandrosion.Sp_differentiableAt
#print axioms Pandrosion.Sp_hasDerivAt
#print axioms Pandrosion.Sp_mul_one_sub
#print axioms Pandrosion.Sp_one
#print axioms Pandrosion.Sp_pos
#print axioms Pandrosion.Sp_sub_factor
#print axioms Pandrosion.T1_rate
#print axioms Pandrosion.T2_rate
#print axioms Pandrosion.T3_rate
#print axioms Pandrosion.abc_orbital_b_lower
#print axioms Pandrosion.abc_orbital_b_upper
#print axioms Pandrosion.abc_orbital_factorization
#print axioms Pandrosion.abc_orbital_sandwich
#print axioms Pandrosion.aitken_denom_at_root
#print axioms Pandrosion.aitken_exact_geometric
#print axioms Pandrosion.aitken_pandrosion_denominator
#print axioms Pandrosion.aitken_perfect_extrapolation
#print axioms Pandrosion.amortized_bound
#print axioms Pandrosion.analog_bound_decreasing
#print axioms Pandrosion.analog_contraction_in_unit
#print axioms Pandrosion.anchor_fixed_point
#print axioms Pandrosion.anchor_fixed_point_cross
#print axioms Pandrosion.anchor_step_at_root
#print axioms Pandrosion.anchor_step_explicit
#print axioms Pandrosion.anchor_step_numerator
#print axioms Pandrosion.angle_in_range
#print axioms Pandrosion.angle_le_pi_div_four
#print axioms Pandrosion.angle_lt_half_pi
#print axioms Pandrosion.angle_nn
#print axioms Pandrosion.angular_separation
#print axioms Pandrosion.angular_spacing
#print axioms Pandrosion.angular_spacing_decreasing
#print axioms Pandrosion.asymptotic_rate_in_unit
#print axioms Pandrosion.bad_starts_measure_zero
#print axioms Pandrosion.baker_davenport_escape
#print axioms Pandrosion.baker_davenport_x2_escape
#print axioms Pandrosion.base_complexity_bound
#print axioms Pandrosion.basin_depth_x2
#print axioms Pandrosion.basin_entry_near
#print axioms Pandrosion.basin_radius_pos
#print axioms Pandrosion.basin_stability
#print axioms Pandrosion.berkovich_power_series_invariant
#print axioms Pandrosion.bias_bound
#print axioms Pandrosion.bias_tends_zero
#print axioms Pandrosion.bilu_tichy_cross_determinant
#print axioms Pandrosion.bilu_tichy_headline
#print axioms Pandrosion.bilu_tichy_orbital_unique
#print axioms Pandrosion.block_descent_ratio_lt_one
#print axioms Pandrosion.block_descent_ratio_pos
#print axioms Pandrosion.bombieri_pila_orbital
#print axioms Pandrosion.bombieri_pila_projective
#print axioms Pandrosion.bounded_height_complement
#print axioms Pandrosion.brauer_siegel_effective_base
#print axioms Pandrosion.canonical_contraction
#print axioms Pandrosion.canonical_ratio
#print axioms Pandrosion.catalan_cert_x2_neg
#print axioms Pandrosion.catalan_disjoint
#print axioms Pandrosion.catalan_neg_unique
#print axioms Pandrosion.catalan_no_collision
#print axioms Pandrosion.catalan_orbital_headline
#print axioms Pandrosion.catalan_pos_unique
#print axioms Pandrosion.catalan_unsigned_unique
#print axioms Pandrosion.cauchy_R_gt_bound
#print axioms Pandrosion.cauchy_R_pos
#print axioms Pandrosion.cauchy_schwarz_trace_d3
#print axioms Pandrosion.centroid_correction_pos
#print axioms Pandrosion.character_sum_dvd
#print axioms Pandrosion.character_sum_not_dvd
#print axioms Pandrosion.chebyshev_halley_coeff_s3X
#print axioms Pandrosion.chebyshev_halley_coeff_s6
#print axioms Pandrosion.complex_conjugate_symmetry
#print axioms Pandrosion.complex_contraction_ratio
#print axioms Pandrosion.complex_descent_neg
#print axioms Pandrosion.complex_no_parasitic_attractors
#print axioms Pandrosion.complex_quadratic_convergence
#print axioms Pandrosion.complex_roots_count
#print axioms Pandrosion.conservation_polynomial_at_root
#print axioms Pandrosion.containment_at_canonical_radius
#print axioms Pandrosion.contraction_bounded_below
#print axioms Pandrosion.contraction_excludes_lattes
#print axioms Pandrosion.contraction_factor_lt_one
#print axioms Pandrosion.contraction_factor_pos
#print axioms Pandrosion.contraction_from_negative_ratio
#print axioms Pandrosion.contraction_general
#print axioms Pandrosion.contraction_identity_p2
#print axioms Pandrosion.contraction_iterate
#print axioms Pandrosion.contraction_p3
#print axioms Pandrosion.contraction_p4
#print axioms Pandrosion.contraction_p5
#print axioms Pandrosion.contraction_rate_bounded_above
#print axioms Pandrosion.contraction_rate_pos
#print axioms Pandrosion.contraction_ratio_at_fixpoint
#print axioms Pandrosion.contraction_ratio_lt_one
#print axioms Pandrosion.contraction_ratio_nonneg
#print axioms Pandrosion.contraction_ratio_pos
#print axioms Pandrosion.contraction_ratio_positive
#print axioms Pandrosion.contraction_sandwich
#print axioms Pandrosion.contraction_step_p2
#print axioms Pandrosion.convergence_p2
#print axioms Pandrosion.convergence_to_zero
#print axioms Pandrosion.cos_angle_is_pos
#print axioms Pandrosion.cos_angle_lt_one
#print axioms Pandrosion.cos_angle_lt_unit
#print axioms Pandrosion.cos_angle_pos
#print axioms Pandrosion.cos_in_unit_interval
#print axioms Pandrosion.critical_line_ratio
#print axioms Pandrosion.critical_line_ratio_pos
#print axioms Pandrosion.cross_det_pattern_p2
#print axioms Pandrosion.cross_det_pattern_p3
#print axioms Pandrosion.cross_det_pattern_p4
#print axioms Pandrosion.cross_det_pattern_p5
#print axioms Pandrosion.cross_determinant
#print axioms Pandrosion.cross_determinant_nonzero
#print axioms Pandrosion.cross_determinant_p2
#print axioms Pandrosion.cross_determinant_p4
#print axioms Pandrosion.cross_determinant_p5
#print axioms Pandrosion.cube_diff_factor
#print axioms Pandrosion.cube_diff_scaled
#print axioms Pandrosion.cube_root_fixpoint
#print axioms Pandrosion.cubic_factorization
#print axioms Pandrosion.curvature_pos
#print axioms Pandrosion.denom_multiplier_lower_bound
#print axioms Pandrosion.denominator_cubed_at_root
#print axioms Pandrosion.derivative_denominator
#print axioms Pandrosion.derivative_numerator
#print axioms Pandrosion.descent_angle_in_range
#print axioms Pandrosion.descent_constant_bounded
#print axioms Pandrosion.descent_constant_pos
#print axioms Pandrosion.descent_eps_bound
#print axioms Pandrosion.descent_negative
#print axioms Pandrosion.descent_strict
#print axioms Pandrosion.descent_sum_negative
#print axioms Pandrosion.descent_target_value_neg
#print axioms Pandrosion.descent_term_neg
#print axioms Pandrosion.dft_periodicity
#print axioms Pandrosion.disc_int_ge_one
#print axioms Pandrosion.displacement_bound
#print axioms Pandrosion.distance_decreases_general
#print axioms Pandrosion.distance_decreases_p2
#print axioms Pandrosion.distance_decreases_p3
#print axioms Pandrosion.distance_decreases_p4
#print axioms Pandrosion.distance_decreases_p5
#print axioms Pandrosion.dml_abs_return_set_subsingleton
#print axioms Pandrosion.dml_orbit_injection
#print axioms Pandrosion.dml_return_set_finite
#print axioms Pandrosion.dml_return_set_subsingleton
#print axioms Pandrosion.effective_distance_bound
#print axioms Pandrosion.effective_distance_bound_amplified
#print axioms Pandrosion.effective_irrationality_proximity
#print axioms Pandrosion.effective_skolem_mahler_lech
#print axioms Pandrosion.effective_thue_envelope
#print axioms Pandrosion.effective_thue_orbital
#print axioms Pandrosion.effective_thue_orbital_linear
#print axioms Pandrosion.effective_thue_pandrosion
#print axioms Pandrosion.eigenvalue_product
#print axioms Pandrosion.energy_decreasing
#print axioms Pandrosion.energy_equality_symmetric
#print axioms Pandrosion.energy_excess_lt_one
#print axioms Pandrosion.energy_excess_positive
#print axioms Pandrosion.energy_excess_quadratic_decay
#print axioms Pandrosion.energy_normalizes
#print axioms Pandrosion.energy_zero_of_zero_vector
#print axioms Pandrosion.epoch_contraction
#print axioms Pandrosion.epoch_contraction_factor
#print axioms Pandrosion.epoch_contraction_strong
#print axioms Pandrosion.epoch_count_bound
#print axioms Pandrosion.epoch_count_constant
#print axioms Pandrosion.epoch_descent_equals_d_times_log
#print axioms Pandrosion.epoch_descent_neg
#print axioms Pandrosion.epoch_descent_negative
#print axioms Pandrosion.epoch_strict_contraction
#print axioms Pandrosion.erdos_mahler_orbital_escape
#print axioms Pandrosion.erdos_mahler_sparse_divergence
#print axioms Pandrosion.error_after_n_steps_p2
#print axioms Pandrosion.error_nonneg
#print axioms Pandrosion.euler_factor_converges
#print axioms Pandrosion.exp_integral_pos
#print axioms Pandrosion.exp_neg_one_lt_one
#print axioms Pandrosion.extra_fixed_multiplier_normSq
#print axioms Pandrosion.extra_fixed_multiplier_normSq_gt_one
#print axioms Pandrosion.extra_fixed_multiplier_norm_gt_one
#print axioms Pandrosion.faltings_orbital_box_extinction
#print axioms Pandrosion.faltings_orbital_effective_bound
#print axioms Pandrosion.far_anchor_correction_decay
#print axioms Pandrosion.far_anchor_ratio_limit
#print axioms Pandrosion.fewer_iterations
#print axioms Pandrosion.fft_cost
#print axioms Pandrosion.field_smooth_on_circle
#print axioms Pandrosion.fixed_point_equation
#print axioms Pandrosion.fixed_point_iff
#print axioms Pandrosion.fixed_point_unique_p2
#print axioms Pandrosion.full_circle_coverage
#print axioms Pandrosion.gbm_exponent_pos
#print axioms Pandrosion.gbm_probability_le_one
#print axioms Pandrosion.gbm_probability_pos
#print axioms Pandrosion.geometric_convergence_rate
#print axioms Pandrosion.geometric_strictly_decreasing
#print axioms Pandrosion.geometric_sum_pos
#print axioms Pandrosion.global_basin_stability
#print axioms Pandrosion.global_contraction
#print axioms Pandrosion.global_convergence
#print axioms Pandrosion.h_at_one_lt_one
#print axioms Pandrosion.h_at_one_pos
#print axioms Pandrosion.h_at_zero_pos
#print axioms Pandrosion.h_deriv_at_fixpoint_p2
#print axioms Pandrosion.h_deriv_p2
#print axioms Pandrosion.h_diff_general
#print axioms Pandrosion.h_hasDerivAt
#print axioms Pandrosion.h_lt_one
#print axioms Pandrosion.h_p2
#print axioms Pandrosion.h_p3
#print axioms Pandrosion.h_pos
#print axioms Pandrosion.h_strict_mono_p2
#print axioms Pandrosion.half_plane_contraction
#print axioms Pandrosion.hall_geometric_escape
#print axioms Pandrosion.hall_normalized_escape
#print axioms Pandrosion.hall_orbital_dichotomy
#print axioms Pandrosion.hall_orbital_envelope
#print axioms Pandrosion.hall_sparsity_index_bound
#print axioms Pandrosion.hall_sparsity_value_unique
#print axioms Pandrosion.hall_threshold_geometric
#print axioms Pandrosion.hall_threshold_linear
#print axioms Pandrosion.hasDerivAt_inv_one_add
#print axioms Pandrosion.hilbert_irreducibility_orbital
#print axioms Pandrosion.hilbert_polya_hermitian_U
#print axioms Pandrosion.hilbert_polya_hermitian_V
#print axioms Pandrosion.hilbert_polya_invariant
#print axioms Pandrosion.hilbert_quantitative_gap
#print axioms Pandrosion.homotopy_stability
#print axioms Pandrosion.hyperelliptic_polynomial_isogeny
#print axioms Pandrosion.initial_norm_x2
#print axioms Pandrosion.injective_is_wandering
#print axioms Pandrosion.int_cast_abs_ge_one
#print axioms Pandrosion.int_strict_gap
#print axioms Pandrosion.intersection_equation
#print axioms Pandrosion.iterated_epoch_bound
#print axioms Pandrosion.iterated_kinematic_contraction
#print axioms Pandrosion.iterations_positive
#print axioms Pandrosion.kinematic_contraction
#print axioms Pandrosion.lagrange_d2
#print axioms Pandrosion.lang_orbital_affine_escape
#print axioms Pandrosion.laplace_series_term_decays
#print axioms Pandrosion.large_alpha_regime
#print axioms Pandrosion.large_alpha_regime_pos
#print axioms Pandrosion.laurent_s_unit_headline
#print axioms Pandrosion.lehmer_bridge_d2
#print axioms Pandrosion.lehmer_bridge_d3
#print axioms Pandrosion.lehmer_orbital_headline
#print axioms Pandrosion.lehmer_quadratic_lower
#print axioms Pandrosion.limit_regime_lt_one
#print axioms Pandrosion.limit_regime_nonneg
#print axioms Pandrosion.liouville_amplified_geometric
#print axioms Pandrosion.log_cos_neg
#print axioms Pandrosion.log_div_eq_sub_log
#print axioms Pandrosion.log_inv_contraction_pos
#print axioms Pandrosion.log_le_sub_one
#print axioms Pandrosion.log_one_plus_bound_weaker
#print axioms Pandrosion.log_prod_eq_sum_log
#print axioms Pandrosion.mahler_yu_integer_gap
#print axioms Pandrosion.mahler_yu_orbit_nonzero
#print axioms Pandrosion.mahler_yu_orbital_gap
#print axioms Pandrosion.mahler_yu_real_gap
#print axioms Pandrosion.matrix_pandrosion_oscillation
#print axioms Pandrosion.mihailescu_orbital_unique
#print axioms Pandrosion.mm_finite_set_finite
#print axioms Pandrosion.mm_no_orbital_preperiodic
#print axioms Pandrosion.mm_no_preperiodic_dense_finite
#print axioms Pandrosion.mm_pandrosion_headline
#print axioms Pandrosion.mm_singleton_dichotomy
#print axioms Pandrosion.mm_singleton_subsingleton
#print axioms Pandrosion.mm_thue_hypersurface_subsingleton
#print axioms Pandrosion.mobius_error_bound
#print axioms Pandrosion.mobius_limit
#print axioms Pandrosion.monotone_from_above_p2
#print axioms Pandrosion.monotone_from_below_p2
#print axioms Pandrosion.mordell_abc_A_isolation
#print axioms Pandrosion.mordell_abc_X_isolation
#print axioms Pandrosion.mordell_abc_delta_shift
#print axioms Pandrosion.morton_silverman_escape
#print axioms Pandrosion.morton_silverman_no_periodic
#print axioms Pandrosion.morton_silverman_no_preperiodic
#print axioms Pandrosion.morton_silverman_wandering
#print axioms Pandrosion.multi_start_all_roots_hit
#print axioms Pandrosion.multi_start_completeness
#print axioms Pandrosion.multi_start_injective
#print axioms Pandrosion.multiplicative_exp_growth
#print axioms Pandrosion.multistart_distinct_roots_guarantee
#print axioms Pandrosion.multistart_step_at_root
#print axioms Pandrosion.near_identity_regime
#print axioms Pandrosion.newton_derivative_numerator
#print axioms Pandrosion.newton_from_pandrosion
#print axioms Pandrosion.newton_girard_d2
#print axioms Pandrosion.newton_girard_d3
#print axioms Pandrosion.newton_is_pandrosion_cross
#print axioms Pandrosion.newton_quadratic_constant_pos
#print axioms Pandrosion.newton_ratio_at_root
#print axioms Pandrosion.newton_ratio_negative
#print axioms Pandrosion.next_denom_growth
#print axioms Pandrosion.next_numer_nonneg
#print axioms Pandrosion.no_periodic_orbit
#print axioms Pandrosion.no_two_cycle
#print axioms Pandrosion.non_asymptotic_bound
#print axioms Pandrosion.norm_amplification
#print axioms Pandrosion.norm_amplification_p2
#print axioms Pandrosion.norm_amplification_x2_verify
#print axioms Pandrosion.norm_geometric_growth
#print axioms Pandrosion.norm_linear_lower_bound
#print axioms Pandrosion.norm_never_zero
#print axioms Pandrosion.norm_product_nonzero
#print axioms Pandrosion.norm_step1_x2
#print axioms Pandrosion.norm_strict_increase
#print axioms Pandrosion.norm_values_distinct
#print axioms Pandrosion.normalized_descent_neg
#print axioms Pandrosion.northcott_cardinality_bound
#print axioms Pandrosion.northcott_finite
#print axioms Pandrosion.northcott_implies_no_preperiodic_orbital
#print axioms Pandrosion.northcott_index_inclusion
#print axioms Pandrosion.northcott_injective_on_bounded
#print axioms Pandrosion.northcott_orbital_headline
#print axioms Pandrosion.northcott_x2_height_1
#print axioms Pandrosion.northcott_x2_height_100
#print axioms Pandrosion.not_converges_to_root_zero
#print axioms Pandrosion.numer_multiplier_nonneg
#print axioms Pandrosion.omega_ne_one
#print axioms Pandrosion.omega_pow_eq_one
#print axioms Pandrosion.omega_pow_ne_one_of_not_dvd
#print axioms Pandrosion.optimal_start_in_interval
#print axioms Pandrosion.optimal_start_in_unit
#print axioms Pandrosion.orbit_in_interval
#print axioms Pandrosion.orbital_triple_step
#print axioms Pandrosion.orbital_triple_sum
#print axioms Pandrosion.orbital_triple_zero
#print axioms Pandrosion.orthogonality_same
#print axioms Pandrosion.oscillation_polynomial_at_root
#print axioms Pandrosion.oscillation_ratio_at_root
#print axioms Pandrosion.oscillatory_for_x_lt_one
#print axioms Pandrosion.oscillatory_ratio_bounded
#print axioms Pandrosion.oscillatory_ratio_pos
#print axioms Pandrosion.output_at_fixed_point
#print axioms Pandrosion.output_at_fixpoint
#print axioms Pandrosion.output_formula_step
#print axioms Pandrosion.output_identity
#print axioms Pandrosion.output_positive
#print axioms Pandrosion.pade_hypergeometric_residual
#print axioms Pandrosion.padic_prime_segregation
#print axioms Pandrosion.pandrosion_basin_depth
#print axioms Pandrosion.pandrosion_basin_depth_gt_one
#print axioms Pandrosion.pandrosion_classification_novel
#print axioms Pandrosion.pandrosion_contraction_ratio_3
#print axioms Pandrosion.pandrosion_denom_eq
#print axioms Pandrosion.pandrosion_derivative_value
#print axioms Pandrosion.pandrosion_fixpoint_p2
#print axioms Pandrosion.pandrosion_generalized_denom_pos
#print axioms Pandrosion.pandrosion_generalized_fixpoint
#print axioms Pandrosion.pandrosion_global_basin_stability
#print axioms Pandrosion.pandrosion_halley_agree_iff
#print axioms Pandrosion.pandrosion_halley_cross
#print axioms Pandrosion.pandrosion_is_not_logarithmic_derivative
#print axioms Pandrosion.pandrosion_kinematic_conservation
#print axioms Pandrosion.pandrosion_lehmer_d2
#print axioms Pandrosion.pandrosion_lehmer_d3
#print axioms Pandrosion.pandrosion_newton_cross
#print axioms Pandrosion.pandrosion_not_in_chebyshev_halley
#print axioms Pandrosion.pandrosion_not_lattes
#print axioms Pandrosion.pandrosion_oscillation_identity
#print axioms Pandrosion.pandrosion_p2_identity
#print axioms Pandrosion.pandrosion_step_x2
#print axioms Pandrosion.pandrosion_strict_contraction
#print axioms Pandrosion.parseval_dc_term
#print axioms Pandrosion.parseval_structure
#print axioms Pandrosion.pell_initial_norm_x2
#print axioms Pandrosion.pell_norm_step1_x2
#print axioms Pandrosion.pell_pandrosion_identity
#print axioms Pandrosion.pell_step_x2
#print axioms Pandrosion.pell_verify_x2
#print axioms Pandrosion.phase1_contraction
#print axioms Pandrosion.phase2_contraction
#print axioms Pandrosion.phi_at_initial_x2
#print axioms Pandrosion.phi_at_x2_initial
#print axioms Pandrosion.phi_at_x2_initial_abs
#print axioms Pandrosion.phi_at_x3_initial
#print axioms Pandrosion.phi_at_x3_initial_abs
#print axioms Pandrosion.phi_p2_at_x2
#print axioms Pandrosion.phi_p2_at_x2_abs
#print axioms Pandrosion.phi_p2_nonneg_squares
#print axioms Pandrosion.pi_pos'
#print axioms Pandrosion.pi_sq_pos
#print axioms Pandrosion.pillai_cert_x2_escape_42
#print axioms Pandrosion.pillai_escape
#print axioms Pandrosion.pillai_escape_explicit
#print axioms Pandrosion.pillai_finite
#print axioms Pandrosion.pillai_orbital_dichotomy
#print axioms Pandrosion.pillai_unique
#print axioms Pandrosion.pillai_unique_signed
#print axioms Pandrosion.pillai_value_set_infinite
#print axioms Pandrosion.polynomial_intersection_identity
#print axioms Pandrosion.positive_reals_converge
#print axioms Pandrosion.potential_positive
#print axioms Pandrosion.pow_sub_factor
#print axioms Pandrosion.power_sum_2_d3_eq_zero_iff
#print axioms Pandrosion.power_sum_2_d3_nn
#print axioms Pandrosion.power_sum_denominator_pos
#print axioms Pandrosion.precision_pos
#print axioms Pandrosion.principal_fixed_point
#print axioms Pandrosion.product_containment_decay
#print axioms Pandrosion.product_contraction
#print axioms Pandrosion.product_contraction_tendsto
#print axioms Pandrosion.product_descent_bound
#print axioms Pandrosion.progress_rate_pos
#print axioms Pandrosion.psl_compound_d3
#print axioms Pandrosion.psl_headline_d3
#print axioms Pandrosion.psl_trace_d2
#print axioms Pandrosion.psl_trace_d3
#print axioms Pandrosion.quadratic_beats_linear
#print axioms Pandrosion.quadratic_form_upper_bound
#print axioms Pandrosion.quantum_phase_lock_U
#print axioms Pandrosion.quantum_phase_lock_V
#print axioms Pandrosion.quantum_phase_lock_temporal
#print axioms Pandrosion.quantum_spectral_pandrosion_oscillation
#print axioms Pandrosion.radial_contraction_bound
#print axioms Pandrosion.rate_abs_lt_one
#print axioms Pandrosion.ratio_complement
#print axioms Pandrosion.re_nontrivial_sum
#print axioms Pandrosion.re_roots_sum_zero
#print axioms Pandrosion.reanchor_at_root
#print axioms Pandrosion.reduced_ratio_lt
#print axioms Pandrosion.regularization_of_singularity
#print axioms Pandrosion.residual_ratio_at_root
#print axioms Pandrosion.root_ratio_lt_one
#print axioms Pandrosion.root_to_radius_ratio_lt_one
#print axioms Pandrosion.root_to_radius_ratio_pos
#print axioms Pandrosion.roots_eq_degree
#print axioms Pandrosion.roots_of_unity_sum
#print axioms Pandrosion.s_unit_difference_unique
#print axioms Pandrosion.s_unit_factorization
#print axioms Pandrosion.s_unit_index_bound
#print axioms Pandrosion.s_unit_second_unique
#print axioms Pandrosion.s_unit_u_plus_v_eq_one
#print axioms Pandrosion.scaling_identity
#print axioms Pandrosion.schmidt_orbital_height_bound
#print axioms Pandrosion.schmidt_orbital_height_lower
#print axioms Pandrosion.schmidt_orbital_relation
#print axioms Pandrosion.second_derivative_denominator
#print axioms Pandrosion.second_derivative_numerator
#print axioms Pandrosion.second_derivative_value
#print axioms Pandrosion.skolem_escape_cutoff
#print axioms Pandrosion.skolem_non_escape_bounded
#print axioms Pandrosion.skolem_return_dichotomy
#print axioms Pandrosion.skolem_return_finite
#print axioms Pandrosion.skolem_return_subsingleton
#print axioms Pandrosion.skolem_x2_cutoff_100
#print axioms Pandrosion.skolem_x2_cutoff_million
#print axioms Pandrosion.skolem_zero_set_empty
#print axioms Pandrosion.skolem_zero_set_finite
#print axioms Pandrosion.smale_conditional_contraction
#print axioms Pandrosion.smale_d2
#print axioms Pandrosion.smale_d3
#print axioms Pandrosion.smale_no_parasitic_attractors
#print axioms Pandrosion.smale_step_count
#print axioms Pandrosion.smale_total_cost
#print axioms Pandrosion.smale_universal_descent_termination
#print axioms Pandrosion.smyth_discriminant_bound
#print axioms Pandrosion.smyth_orbital_strict_bound
#print axioms Pandrosion.sp_at_least_one
#print axioms Pandrosion.sp_sum_nonneg
#print axioms Pandrosion.spectral_coeff_decays
#print axioms Pandrosion.spectral_decay
#print axioms Pandrosion.spectral_decay_improves
#print axioms Pandrosion.spectral_det_d2
#print axioms Pandrosion.spectral_det_d3
#print axioms Pandrosion.spectral_detection
#print axioms Pandrosion.spectral_diophantine_amplification
#print axioms Pandrosion.spectral_eigenvalue_sq
#print axioms Pandrosion.spectral_energy_excess_nonneg
#print axioms Pandrosion.spectral_energy_nonneg
#print axioms Pandrosion.spectral_left_half_plane
#print axioms Pandrosion.spectral_radius_lt_one
#print axioms Pandrosion.sss_cert_equal
#print axioms Pandrosion.sss_cert_sharp_equal
#print axioms Pandrosion.sss_cert_trivial
#print axioms Pandrosion.sss_headline_d3
#print axioms Pandrosion.sss_lower_bound_d3
#print axioms Pandrosion.sss_normalization_d3
#print axioms Pandrosion.standard_vs_anchor
#print axioms Pandrosion.start_improves
#print axioms Pandrosion.steffensen_at_fixpoint
#print axioms Pandrosion.steffensen_beats_newton_ratio
#print axioms Pandrosion.steffensen_constant_bounded
#print axioms Pandrosion.steffensen_constant_factor
#print axioms Pandrosion.steffensen_constant_pos
#print axioms Pandrosion.steffensen_denominator
#print axioms Pandrosion.steffensen_quadratic_constant
#print axioms Pandrosion.steffensen_quadratic_constant_p3
#print axioms Pandrosion.stewart_yu_c_orbital
#print axioms Pandrosion.stewart_yu_orbital_bound
#print axioms Pandrosion.sub_dvd_pow_sub_pow_manual
#print axioms Pandrosion.sym_form_pos
#print axioms Pandrosion.t3_converges
#print axioms Pandrosion.t3_cubic_rate
#print axioms Pandrosion.t3_rate_d2
#print axioms Pandrosion.t3_rate_d3
#print axioms Pandrosion.t3_rate_d4
#print axioms Pandrosion.t3_rate_p3
#print axioms Pandrosion.telescopic_zeta_difference
#print axioms Pandrosion.telescoping_factor_near_one
#print axioms Pandrosion.termination
#print axioms Pandrosion.three_step_contraction
#print axioms Pandrosion.three_steps_at_root
#print axioms Pandrosion.thue_abs_value_injective
#print axioms Pandrosion.thue_orbital_bound
#print axioms Pandrosion.thue_orbital_escape
#print axioms Pandrosion.thue_pandrosion_progression
#print axioms Pandrosion.thue_strict_improvement_qualitative
#print axioms Pandrosion.thue_value_injective
#print axioms Pandrosion.thue_x2_orbit_bound
#print axioms Pandrosion.tn_converges
#print axioms Pandrosion.trace_int_d2
#print axioms Pandrosion.trace_int_d3
#print axioms Pandrosion.trace_nonzero_lower
#print axioms Pandrosion.turing_entropy_lipschitz_bound
#print axioms Pandrosion.unconditional_stability
#print axioms Pandrosion.universal_contraction_ratio
#print axioms Pandrosion.universal_diophantine_pandrosion
#print axioms Pandrosion.universal_epoch_bound
#print axioms Pandrosion.universal_epoch_contraction
#print axioms Pandrosion.vojta_dim2_cube_bound
#print axioms Pandrosion.vojta_dim2_orbital_push
#print axioms Pandrosion.vojta_orbital_log
#print axioms Pandrosion.vojta_orbital_multiplicative
#print axioms Pandrosion.vojta_orbital_sparsity
#print axioms Pandrosion.vojta_orbital_step
#print axioms Pandrosion.vojta_pandrosion_headline
#print axioms Pandrosion.vojta_real_lift
#print axioms Pandrosion.volume_singleton_zero_complex
#print axioms Pandrosion.voronoi_basin_inclusivity
#print axioms Pandrosion.voronoi_halfplane_affine
#print axioms Pandrosion.voronoi_halfplane_convex
#print axioms Pandrosion.wandering_not_periodic
#print axioms Pandrosion.wandering_not_preperiodic
#print axioms Pandrosion.zeta_higher_d3_m0
#print axioms Pandrosion.zeta_higher_d3_m1
#print axioms Pandrosion.zeta_normalisation_d3
#print axioms Pandrosion.zeta_vanishing_d2
#print axioms Pandrosion.zeta_vanishing_d3
#print axioms Pandrosion.zsygmondy_orbit_nonzero
#print axioms Pandrosion.zsygmondy_orbital_increment
-- END GENERATED AXIOM AUDIT
