/-
  Axiom audit file — regenerated by scripts/strict_check.sh.
  The body between the markers below is overwritten on every run with
  `#print axioms Pandrosion.X` lines for every theorem/lemma discovered
  under Pandrosion/.
-/
import Pandrosion

-- BEGIN GENERATED AXIOM AUDIT
-- END GENERATED AXIOM AUDIT
